import type { Metadata } from "next"
import ThemeClient from "./ThemeClient"
import Script from "next/script"

export const metadata : Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children } : {children : React.ReactNode}) {
  return (
    <html>
      <Script src="https://cdn.jsdelivr.net/npm/gifler@0.1.0/gifler.min.js"/>
      <body>
        <ThemeClient>
          <div>
            {children}
          </div>
        </ThemeClient>
      </body>
    </html>
  )
}
